# base on prebuilt image 'iree_base' only
ARG BASE_IMAGE=iree_base:latest
FROM ${BASE_IMAGE}

LABEL maintainer="nikshuang@sina.com"

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    clang \
    ninja-build \
    librdmacm-dev \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV IREE_BUILD_DIR=/root/iree-build
ENV IREE_RISCV_BUILD_DIR=/root/iree-riscv

COPY iree /root/iree
WORKDIR /root/iree

# predownload amdgpu bitcode
RUN mkdir -p ${IREE_BUILD_DIR}/compiler/plugins/target/ROCM/
RUN cp predownload/amdgpu-device-libs-llvm-6086c272a3a59eb0b6b79dcbe00486bf4461856a.tgz \
	${IREE_BUILD_DIR}/compiler/plugins/target/ROCM/_fetch_device_libs.tgz -v

ARG BUILD_TYPE=Release
ARG RISCV_COMPILER_FLAGS=-O3

ENV RISCV_COMPILER_FLAGS=${RISCV_COMPILER_FLAGS}

RUN cmake -GNinja -B ${IREE_BUILD_DIR} \
  -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
  -DRISCV_COMPILER_FLAGS=${RISCV_COMPILER_FLAGS} \
  -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
  -DCMAKE_INSTALL_PREFIX=${IREE_BUILD_DIR}/install \
  -DCMAKE_C_COMPILER=clang \
  -DCMAKE_CXX_COMPILER=clang++ \
  -DIREE_BUILD_PYTHON_BINDINGS=ON  \
  -DPython3_EXECUTABLE="$(which python3)" \
  .
RUN cmake --build ${IREE_BUILD_DIR} --target install

#RUN echo -e "\ny\ny\n" | ./build_tools/riscv/riscv_bootstrap.sh
ENV RISCV_TOOLCHAIN_ROOT=/root/iree/riscv/toolchain/clang/linux/RISCV
ENV QEMU_BIN=/root/iree/riscv/qemu/linux/RISCV/qemu-riscv64

RUN cmake -GNinja -B ${IREE_RISCV_BUILD_DIR} \
  -DCMAKE_BUILD_TYPE=${BUILD_TYPE} \
  -DRISCV_COMPILER_FLAGS=${RISCV_COMPILER_FLAGS} \
  -DCMAKE_TOOLCHAIN_FILE="./build_tools/cmake/riscv.toolchain.cmake" \
  -DIREE_HOST_BIN_DIR=$(realpath ${IREE_BUILD_DIR}/install/bin) \
  -DRISCV_CPU=linux-riscv_64 \
  -DIREE_BUILD_COMPILER=OFF \
  -DRISCV_TOOLCHAIN_ROOT=${RISCV_TOOLCHAIN_ROOT} \
  -DIREE_ENABLE_CPUINFO=OFF \
  .
RUN cmake --build ${IREE_RISCV_BUILD_DIR}

## test
#RUN $IREE_BUILD_DIR/install/bin/iree-compile \
#  --iree-hal-target-backends=vmvx \
#  samples/models/simple_abs.mlir \
#  -o /tmp/simple_abs_vmvx.vmfb
#
#RUN ${QEMU_BIN} \
#-cpu rv64 \
#-L ${RISCV_TOOLCHAIN_ROOT}/sysroot/ \
#$IREE_RISCV_BUILD_DIR/tools/iree-run-module \
#--device=local-task \
#--module=/tmp/simple_abs_vmvx.vmfb \
#--function=abs \
#--input=fp32=-5
