ARG DEV_IMAGE
FROM ${DEV_IMAGE} as dev_image

FROM ubuntu:22.04

LABEL maintainer="nikshuang@sina.com"

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget \
    vim \
    git \
    python3 \
    python3-pip \
    libxml2 \
    librdmacm-dev \
    libdw1 \
    libglib2.0-0 \
    clang \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN chmod +x Miniconda3-latest-Linux-x86_64.sh
RUN ./Miniconda3-latest-Linux-x86_64.sh -b
RUN echo "PATH=/root/miniconda3/bin:$PATH" >> ~/.bashrc

RUN /root/miniconda3/bin/conda create -n py3_11 python=3.11
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "py3_11", "/bin/bash", "-c"]

WORKDIR /root
COPY iree/torch-mlir torch-mlir
COPY iree/integrations/tensorflow/python_projects/iree_tf iree_tf

# # install torch-mlir
# WORKDIR /root/torch-mlir
# RUN pip install --upgrade pip
# RUN python -m pip install -r requirements.txt
# RUN python -m pip install -r torchvision-requirements.txt
# RUN mkdir -p build
# RUN cmake -GNinja -Bbuild \
#   -DCMAKE_BUILD_TYPE=Release \
#   -DPython3_FIND_VIRTUALENV=ONLY \
#   -DLLVM_ENABLE_PROJECTS=mlir \
#   -DLLVM_EXTERNAL_PROJECTS="torch-mlir" \
#   -DLLVM_EXTERNAL_TORCH_MLIR_SOURCE_DIR="$PWD" \
#   -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
#   -DLLVM_TARGETS_TO_BUILD=host \
#   externals/llvm-project/llvm
# RUN cmake --build build --target tools/torch-mlir/all
# RUN cmake --build build --target install

# ENV PYTHONPATH=/root/torch-mlir/build/tools/torch-mlir/python_packages/torch_mlir:/root/torch-mlir/projects/pt1/examples

# install torch-mlir torchvison
RUN pip install --upgrade pip
RUN pip install --pre torch-mlir torchvision \
 -f https://llvm.github.io/torch-mlir/package-index/ \
 --extra-index-url https://download.pytorch.org/whl/nightly/cpu

# install transformers
RUN pip install transformers

# install iree-import-tf
RUN pip install tf-nightly
RUN pip install /root/iree_tf

RUN /root/miniconda3/bin/conda init bash
RUN echo "conda activate py3_11" >> ~/.bashrc

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /root
COPY iree/examples examples
COPY iree/scripts scripts
COPY iree/riscv riscv
COPY --from=dev_image /root/iree-build /root/iree-build
COPY --from=dev_image /root/iree-riscv /root/iree-riscv

RUN echo "export PATH=/root/scripts:/root/iree-build/install/bin:/root/iree-riscv/tools:$PATH" >> ~/.bashrc

