FROM ubuntu:22.04

LABEL maintainer="nikshuang@sina.com"

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    python3 \
    python3-pip \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# install onnx-tf tf onnxruntime(used for fix dynamic shape)
RUN pip install onnx-tf tensorflow tensorflow_probability onnxruntime

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /root
