# base on prebuilt image 'iree_base' only
ARG base_image=iree_base
FROM ${base_image}

LABEL maintainer="nikshuang@sina.com"

cmake -GNinja -B ../iree-build-base/ \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_BUILD_WITH_INSTALL_RPATH=ON \
  -DCMAKE_C_COMPILER=${CC}\
  -DCMAKE_CXX_COMPILER=${CXX} \
  -DCMAKE_INSTALL_PREFIX=../iree-build-base/install \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  .

cmake --build ../iree-build-base/ --target install

# Install dependent packages
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    wget \
    vim \
    python3 \
    python3-pip \
    librdmacm-dev \
    ssh \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN wget --no-check-certificate https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN chmod +x Miniconda3-latest-Linux-x86_64.sh
RUN ./Miniconda3-latest-Linux-x86_64.sh -b
RUN echo "PATH=/root/miniconda3/bin:$PATH" >> ~/.bashrc

RUN /root/miniconda3/bin/conda create -n iree python=3.11
SHELL ["/root/miniconda3/bin/conda", "run", "-n", "iree", "/bin/bash", "-c"]

# install torch-mlir torchvison
RUN pip install --upgrade pip
RUN pip install --pre torch-mlir torchvision \
  -f https://llvm.github.io/torch-mlir/package-index/ \
  --extra-index-url https://download.pytorch.org/whl/nightly/cpu
# install transformers
RUN pip install transformers

RUN /root/miniconda3/bin/conda init bash
RUN echo "conda activate iree" >> ~/.bashrc

RUN ln -s /usr/bin/python3 /usr/bin/python

WORKDIR /root
COPY examples examples

